import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        whatsapp: {
          50: "#effaf3",
          100: "#dcf6e5",
          200: "#bbeece",
          300: "#89e0aa",
          400: "#51cb80",
          500: "#25D366",
          600: "#1da851",
          700: "#188542",
          800: "#176937",
          900: "#15562f",
          950: "#062f18",
        },
        "on-secondary": "#003731",
        "surface-dim": "#0c141b",
        "surface": "#0c141b",
        "surface-container": "#192028",
        "on-primary-fixed": "#002109",
        "secondary-fixed": "#8ff4e3",
        "inverse-on-surface": "#293139",
        "on-surface-variant": "#bbcbb9",
        "inverse-primary": "#006d2f",
        "secondary-fixed-dim": "#72d8c8",
        "tertiary": "#99e1d4",
        "primary-fixed-dim": "#3de273",
        "surface-bright": "#323a42",
        "error-container": "#93000a",
        "inverse-surface": "#dbe3ed",
        "on-background": "#dbe3ed",
        "on-surface": "#dbe3ed",
        "on-primary-container": "#005523",
        "surface-container-low": "#141c24",
        "surface-variant": "#2e363d",
        "surface-tint": "#3de273",
        "on-tertiary-container": "#005249",
        "on-primary": "#003915",
        "surface-container-lowest": "#070f16",
        "secondary-container": "#34a192",
        "outline": "#869584",
        "on-secondary-container": "#00302a",
        "on-tertiary-fixed": "#00201c",
        "surface-container-high": "#232b32",
        "surface-container-highest": "#2e363d",
        "primary-fixed": "#66ff8e",
        "tertiary-fixed-dim": "#8cd4c7",
        "on-tertiary": "#003731",
        "primary-container": "#25d366",
        "on-tertiary-fixed-variant": "#005047",
        "on-primary-fixed-variant": "#005322",
        "on-secondary-fixed": "#00201c",
        "on-error": "#690005",
        "tertiary-container": "#7ec5b8",
        "outline-variant": "#3c4a3d",
        "on-secondary-fixed-variant": "#005047",
        "error": "#ffb4ab",
        "tertiary-fixed": "#a8f0e3",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-subtle": "pulse-subtle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
