import { WhatsAppOrder } from "./types";

export const INITIAL_MOCK_ORDERS: WhatsAppOrder[] = [
  {
    id: "ord_gf_9801",
    orderNumber: "GF-9801",
    customerName: "Health Nut Supermart",
    customerPhone: "+1 (555) 389-1024",
    status: "pending",
    paymentStatus: "pending",
    items: [
      { id: "itm_1", name: "Premium Raw Phool Makhana (5kg)", quantity: 5, price: 85.0 },
      { id: "itm_2", name: "Classic Salted Roasted Makhana (1kg)", quantity: 10, price: 22.0 },
      { id: "itm_3", name: "Cheese & Herbs Makhana (500g)", quantity: 20, price: 12.5 },
    ],
    subtotal: 895.0,
    deliveryFee: 25.0,
    discount: 50.0,
    totalAmount: 870.0,
    currency: "INR",
    deliveryAddress: "742 Evergreen Terrace, Retail Bay 4, New York, NY",
    notes: "Please ensure double moisture sealing. Contact warehouse on arrival.",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(), // 12 mins ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    whatsappMessageId: "wamid.HBgLMTU1NTM4OTEwMjRVFQIAEhgg",
    isMock: true,
  },
  {
    id: "ord_gf_9800",
    orderNumber: "GF-9800",
    customerName: "Daily Greens Grocery",
    customerPhone: "+1 (555) 742-8819",
    status: "confirmed",
    paymentStatus: "paid",
    items: [
      { id: "itm_4", name: "Peri Peri Spiced Makhana (500g)", quantity: 15, price: 12.5 },
      { id: "itm_5", name: "Mint Pudina Roasted Makhana (250g)", quantity: 20, price: 8.0 },
      { id: "itm_6", name: "Caramel Crunch Makhana (250g)", quantity: 10, price: 8.0 },
    ],
    subtotal: 427.5,
    deliveryFee: 15.0,
    discount: 0.0,
    totalAmount: 442.5,
    currency: "INR",
    deliveryAddress: "128 Mercer St, Floor 1, Soho, New York, NY",
    notes: "Deliver via back alley loading dock.",
    createdAt: new Date(Date.now() - 1000 * 60 * 34).toISOString(), // 34 mins ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    whatsappMessageId: "wamid.HBgLMTU1NTc0Mjg4MTlVFQIAEhgg",
    isMock: true,
  },
  {
    id: "ord_gf_9799",
    orderNumber: "GF-9799",
    customerName: "Sophia Chen (Retail)",
    customerPhone: "+1 (555) 890-4421",
    status: "preparing",
    paymentStatus: "paid",
    items: [
      { id: "itm_7", name: "Classic Salted Roasted Makhana (1kg)", quantity: 2, price: 22.0 },
      { id: "itm_8", name: "Caramel Crunch Makhana (250g)", quantity: 4, price: 8.0 },
    ],
    subtotal: 76.0,
    deliveryFee: 5.0,
    discount: 0,
    totalAmount: 81.0,
    currency: "INR",
    deliveryAddress: "450 Lexington Ave, Suite 1900, New York, NY",
    notes: "Leave with building reception.",
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    whatsappMessageId: "wamid.HBgLMTU1NTg5MDQ0MjFVFQIAEhgg",
    isMock: true,
  },
  {
    id: "ord_gf_9798",
    orderNumber: "GF-9798",
    customerName: "David K. Reynolds",
    customerPhone: "+1 (555) 431-9022",
    status: "out_for_delivery",
    paymentStatus: "paid",
    items: [
      { id: "itm_10", name: "Premium Raw Phool Makhana (5kg)", quantity: 1, price: 85.0 },
    ],
    subtotal: 85.0,
    deliveryFee: 10.0,
    discount: 0,
    totalAmount: 95.0,
    currency: "INR",
    deliveryAddress: "15 Central Park West, Apt 11A, New York, NY",
    notes: "Driver note: Call WhatsApp when 2 minutes away.",
    createdAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    whatsappMessageId: "wamid.HBgLMTU1NTQzMTkwMjJVFQIAEhgg",
    isMock: true,
  },
  {
    id: "ord_gf_9797",
    orderNumber: "GF-9797",
    customerName: "Amara Patel - Organics",
    customerPhone: "+1 (555) 612-3390",
    status: "delivered",
    paymentStatus: "paid",
    items: [
      { id: "itm_13", name: "Peri Peri Spiced Makhana (500g)", quantity: 50, price: 12.5 },
      { id: "itm_14", name: "Cheese & Herbs Makhana (500g)", quantity: 50, price: 12.5 },
    ],
    subtotal: 1250.0,
    deliveryFee: 0.0,
    discount: 100.0,
    totalAmount: 1150.0,
    currency: "INR",
    deliveryAddress: "88 Greenwich St, Retail Space 2, New York, NY",
    notes: "Free shipping for orders over $1000. Delivered to warehouse manager.",
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    whatsappMessageId: "wamid.HBgLMTU1NTYxMjMzOTBVFQIAEhgg",
    isMock: true,
  },
  {
    id: "ord_gf_9796",
    orderNumber: "GF-9796",
    customerName: "Lucas Moreau",
    customerPhone: "+1 (555) 923-1184",
    status: "cancelled",
    paymentStatus: "pending",
    items: [
      { id: "itm_16", name: "Classic Salted Roasted Makhana (1kg)", quantity: 1, price: 22.0 },
      { id: "itm_17", name: "Premium Raw Phool Makhana (5kg)", quantity: 1, price: 85.0 },
    ],
    subtotal: 107.0,
    deliveryFee: 10.0,
    discount: 0,
    totalAmount: 117.0,
    currency: "INR",
    deliveryAddress: "230 E 44th St, New York, NY",
    notes: "Customer cancelled via WhatsApp chatbot due to stock over-estimation.",
    createdAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    whatsappMessageId: "wamid.HBgLMTU1NTkyMzExODRVFQIAEhgg",
    isMock: true,
  },
];
